# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: produce artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: |
            .
            !.git
            !.github
