# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: yarn

      - name: Lint the code
        run: yarn run lint

      - name: Test formatting
        run: yarn run format

      - name: Build the extension
        run: yarn run build

      - name: Store as artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: ./pixelUP-*.zip
